-- Company Table
CREATE TABLE BSMGRIRPGEN001
(
    COM_CODE VARCHAR(4) UNIQUE NOT NULL PRIMARY KEY,
    COM_TEXT VARCHAR(80)       NOT NULL
);

-- Language Table
CREATE TABLE BSMGRIRPGEN002
(
    COM_CODE VARCHAR(4)        NOT NULL,
    LAN_CODE VARCHAR(3) UNIQUE NOT NULL,
    LAN_TEXT VARCHAR(80)       NOT NULL,
    PRIMARY KEY (COM_CODE, LAN_CODE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- Country Table
CREATE TABLE BSMGRIRPGEN003
(
    COM_CODE     VARCHAR(4)        NOT NULL,
    COUNTRY_CODE VARCHAR(3) UNIQUE NOT NULL,
    COUNTRY_TEXT VARCHAR(80)       NOT NULL,
    PRIMARY KEY (COM_CODE, COUNTRY_CODE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- City Table
CREATE TABLE BSMGRIRPGEN004
(
    COM_CODE     VARCHAR(4)  NOT NULL,
    CITY_CODE    VARCHAR(3)  NOT NULL,
    CITY_TEXT    VARCHAR(80) NOT NULL,
    COUNTRY_CODE VARCHAR(3)  NOT NULL,
    PRIMARY KEY (CITY_CODE, COM_CODE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_country FOREIGN KEY (COUNTRY_CODE) REFERENCES BSMGRIRPGEN003 (COUNTRY_CODE)
);

-- Unit Table
CREATE TABLE BSMGRIRPGEN005
(
    COM_CODE       VARCHAR(4)        NOT NULL,
    UNIT_CODE      VARCHAR(3) UNIQUE NOT NULL,
    UNIT_TEXT      VARCHAR(80)       NOT NULL,
    IS_MAIN_UNIT   BOOLEAN,
    MAIN_UNIT_CODE VARCHAR(3),
    PRIMARY KEY (COM_CODE, UNIT_CODE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- Material Table
CREATE TABLE BSMGRIRPMAT001
(
    COM_CODE      VARCHAR(4)        NOT NULL,
    DOC_TYPE      VARCHAR(4) UNIQUE NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80)       NOT NULL,
    IS_PASSIVE    BOOLEAN,
    PRIMARY KEY (COM_CODE, DOC_TYPE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- Material Table
CREATE TABLE BSMGRIRPCCM001
(
    COM_CODE      VARCHAR(4)        NOT NULL,
    DOC_TYPE      VARCHAR(4) UNIQUE NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80)       NOT NULL,
    IS_PASSIVE    BOOLEAN,
    PRIMARY KEY (COM_CODE, DOC_TYPE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- BOM Table
CREATE TABLE BSMGRIRPBOM001
(
    COM_CODE      VARCHAR(4)        NOT NULL,
    DOC_TYPE      VARCHAR(4) UNIQUE NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80)       NOT NULL,
    IS_PASSIVE    BOOLEAN,
    PRIMARY KEY (COM_CODE, DOC_TYPE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- Route Table
CREATE TABLE BSMGRIRPROT001
(
    COM_CODE      VARCHAR(4)        NOT NULL,
    DOC_TYPE      VARCHAR(4) UNIQUE NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80)       NOT NULL,
    IS_PASSIVE    BOOLEAN,
    PRIMARY KEY (COM_CODE, DOC_TYPE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- Work-Center Table
CREATE TABLE BSMGRIRPWCM001
(
    COM_CODE      VARCHAR(4)        NOT NULL,
    DOC_TYPE      VARCHAR(4) UNIQUE NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80)       NOT NULL,
    IS_PASSIVE    BOOLEAN,
    PRIMARY KEY (COM_CODE, DOC_TYPE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- Operation Table
CREATE TABLE BSMGRIRPROT003
(
    COM_CODE      VARCHAR(4)  NOT NULL,
    DOC_TYPE      VARCHAR(4)  NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80) NOT NULL,
    IS_PASSIVE    BOOLEAN,
    PRIMARY KEY (COM_CODE, DOC_TYPE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE)
);

-- Malzeme Bilgileri
CREATE TABLE BSMGRIRPMATHEAD
(
    COM_CODE      VARCHAR(4)     NOT NULL,
    MAT_DOC_TYPE  VARCHAR(4)     NOT NULL,
    MAT_DOC_NUM   VARCHAR(25)    NOT NULL,
    MAT_DOC_FROM  DATE           NOT NULL DEFAULT CURRENT_DATE,
    MAT_DOC_UNTIL DATE           NOT NULL DEFAULT CURRENT_DATE,
    SUPPLY_TYPE   BOOLEAN        NOT NULL DEFAULT TRUE,
    ST_UNIT       VARCHAR(3)     NOT NULL,
    NET_WEIGHT    DECIMAL(12, 3) NOT NULL,
    NW_UNIT       VARCHAR(3)     NOT NULL,
    BRUT_WEIGHT   DECIMAL(12, 3) NOT NULL,
    BW_UNIT       VARCHAR(3)     NOT NULL,
    IS_BOM        BOOLEAN,
    BOM_DOC_TYPE  VARCHAR(4),
    BOM_DOC_NUM   VARCHAR(25),
    IS_ROUTE      BOOLEAN,
    ROT_DOC_TYPE  VARCHAR(4),
    ROT_DOC_NUM   VARCHAR(25),
    IS_DELETED    BOOLEAN, --burada soft delete var sanırsam, bunu postgresql içerisinde halledebiliriz ??
    IS_PASSIVE    BOOLEAN, --burada soft delete var sanırsam, bunu postgresql içerisinde halledebiliriz ??
    PRIMARY KEY (COM_CODE, MAT_DOC_TYPE, MAT_DOC_NUM, MAT_DOC_FROM, MAT_DOC_UNTIL),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_matdoctype FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001 (DOC_TYPE),
    CONSTRAINT fk_syunit FOREIGN KEY (ST_UNIT) REFERENCES BSMGRIRPGEN005 (UNIT_CODE),
    CONSTRAINT fk_nwunit FOREIGN KEY (NW_UNIT) REFERENCES BSMGRIRPGEN005 (UNIT_CODE),
    CONSTRAINT fk_bwunit FOREIGN KEY (BW_UNIT) REFERENCES BSMGRIRPGEN005 (UNIT_CODE),
    CONSTRAINT fk_bomdoctype FOREIGN KEY (BOM_DOC_TYPE) REFERENCES BSMGRIRPBOM001 (DOC_TYPE),
    CONSTRAINT fk_rotdoctype FOREIGN KEY (ROT_DOC_TYPE) REFERENCES BSMGRIRPROT001 (DOC_TYPE)
);

-- Malzeme Bilgileri
CREATE TABLE BSMGRIRPMATTEXT

(
    COM_CODE      VARCHAR(4)   NOT NULL,
    MAT_DOC_TYPE  VARCHAR(4)   NOT NULL,
    MAT_DOC_NUM   VARCHAR(25)  NOT NULL,
    MAT_DOC_FROM  DATE         NOT NULL DEFAULT CURRENT_DATE,
    MAT_DOC_UNTIL DATE         NOT NULL DEFAULT CURRENT_DATE,
    LAN_CODE      VARCHAR(2)   NOT NULL DEFAULT TRUE,
    MATS_TEXT     VARCHAR(50)  NOT NULL,
    MATL_TEXT     VARCHAR(250) NOT NULL,
    PRIMARY KEY (COM_CODE, MAT_DOC_TYPE, MAT_DOC_NUM, MAT_DOC_FROM, MAT_DOC_UNTIL, LAN_CODE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_matdoctype FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001 (DOC_TYPE),
    CONSTRAINT fk_lancode FOREIGN KEY (LAN_CODE) REFERENCES BSMGRIRPGEN002 (LAN_CODE)
);

-- Maliyet Merkezleri
CREATE TABLE BSMGRIRPCCMHEAD
(
    COM_CODE          VARCHAR(4)  NOT NULL,
    CCM_DOC_TYPE      VARCHAR(4)  NOT NULL,
    CCM_DOC_NUM       VARCHAR(25) NOT NULL,
    CCM_DOC_FROM      DATE        NOT NULL DEFAULT CURRENT_DATE,
    CCM_DOC_UNTIL     DATE        NOT NULL DEFAULT CURRENT_DATE,
    MAIN_CCM_DOC_TYPE VARCHAR(4)  NOT NULL DEFAULT TRUE,
    MAIN_CCM_DOC_NUM  VARCHAR(25) NOT NULL,
    IS_DELETED        BOOLEAN,
    IS_PASSIVE        BOOLEAN,
    PRIMARY KEY (COM_CODE, CCM_DOC_TYPE, CCM_DOC_NUM, CCM_DOC_FROM, CCM_DOC_UNTIL),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_ccmdoctype FOREIGN KEY (CCM_DOC_TYPE) REFERENCES BSMGRIRPCCM001 (DOC_TYPE)
);

-- Maliyet Merkezleri
CREATE TABLE BSMGRIRPCCMTEXT
(
    COM_CODE      VARCHAR(4)   NOT NULL,
    CCM_DOC_TYPE  VARCHAR(4)   NOT NULL,
    CCM_DOC_NUM   VARCHAR(25)  NOT NULL,
    CCM_DOC_FROM  DATE         NOT NULL DEFAULT CURRENT_DATE,
    CCM_DOC_UNTIL DATE         NOT NULL DEFAULT CURRENT_DATE,
    LAN_CODE      VARCHAR(3)         NOT NULL DEFAULT CURRENT_DATE,
    CCMS_TEXT     VARCHAR(50)  NOT NULL,
    CCML_TEXT     VARCHAR(250) NOT NULL,
    PRIMARY KEY (COM_CODE, CCM_DOC_TYPE, CCM_DOC_NUM, CCM_DOC_FROM, CCM_DOC_UNTIL),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_ccmdoctype FOREIGN KEY (CCM_DOC_TYPE) REFERENCES BSMGRIRPCCM001 (DOC_TYPE),
    CONSTRAINT fk_lancode FOREIGN KEY (LAN_CODE) REFERENCES BSMGRIRPGEN002 (LAN_CODE)
);

--------------------------------------------

-- Is Merkezleri
CREATE TABLE BSMGRIRPWCMHEAD
(
    COM_CODE          VARCHAR(4)    NOT NULL,
    WCM_DOC_TYPE      VARCHAR(4)    NOT NULL,
    WCM_DOC_NUM       VARCHAR(25)   NOT NULL,
    WCM_DOC_FROM      DATE          NOT NULL DEFAULT CURRENT_DATE,
    WCM_DOC_UNTIL     DATE          NOT NULL DEFAULT CURRENT_DATE,
    MAIN_WCM_DOC_TYPE VARCHAR(4)    NOT NULL,
    MAIN_WCM_DOC_NUM  VARCHAR(25)   NOT NULL,
    CCM_DOC_TYPE      VARCHAR(4)    NOT NULL,
    CCM_DOC_NUM       VARCHAR(25)   NOT NULL,
    WORKTIME          DECIMAL(3, 2) NOT NULL,
    IS_DELETED        BOOLEAN       NOT NULL,
    IS_PASSIVE        BOOLEAN       NOT NULL,
    PRIMARY KEY (COM_CODE, WCM_DOC_TYPE, WCM_DOC_NUM, WCM_DOC_FROM, WCM_DOC_UNTIL),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_wcmdoctype FOREIGN KEY (WCM_DOC_TYPE) REFERENCES BSMGRIRPWCM001 (DOC_TYPE),
    CONSTRAINT fk_ccmdoctype FOREIGN KEY (CCM_DOC_TYPE) REFERENCES BSMGRIRPCCM001 (DOC_TYPE)
);

-- Is Merkezleri
CREATE TABLE BSMGRIRPWCMTEXT
(
    COM_CODE      VARCHAR(4)   NOT NULL,
    WCM_DOC_TYPE  VARCHAR(4)   NOT NULL,
    WCM_DOC_NUM   VARCHAR(25)  NOT NULL,
    WCM_DOC_FROM  DATE         NOT NULL DEFAULT CURRENT_DATE,
    WCM_DOC_UNTIL DATE         NOT NULL DEFAULT CURRENT_DATE,
    LAN_CODE      VARCHAR(2)   NOT NULL,
    WCMS_TEXT     VARCHAR(50)  NOT NULL,
    WCML_TEXT     VARCHAR(250) NOT NULL,
    PRIMARY KEY (COM_CODE, WCM_DOC_TYPE, WCM_DOC_NUM, WCM_DOC_FROM, WCM_DOC_UNTIL, LAN_CODE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_wcmdoctype FOREIGN KEY (WCM_DOC_TYPE) REFERENCES BSMGRIRPWCM001 (DOC_TYPE),
    CONSTRAINT fk_lancode FOREIGN KEY (LAN_CODE) REFERENCES BSMGRIRPGEN002 (LAN_CODE)
);

-- Is Merkezleri
CREATE TABLE BSMGRIRPWCMOPR
(
    COM_CODE      VARCHAR(4)  NOT NULL,
    WCM_DOC_TYPE  VARCHAR(4)  NOT NULL,
    WCM_DOC_NUM   VARCHAR(25) NOT NULL,
    WCM_DOC_FROM  DATE        NOT NULL DEFAULT CURRENT_DATE,
    WCM_DOC_UNTIL DATE        NOT NULL DEFAULT CURRENT_DATE,
    OPR_DOC_TYPE  VARCHAR(4)  NOT NULL,
    PRIMARY KEY (COM_CODE, WCM_DOC_TYPE, WCM_DOC_NUM, WCM_DOC_FROM, WCM_DOC_UNTIL, OPR_DOC_TYPE),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_wcmdoctype FOREIGN KEY (WCM_DOC_TYPE) REFERENCES BSMGRIRPWCM001 (DOC_TYPE)
);

-- Urun Agacları
CREATE TABLE BSMGRIRPBOMHEAD
(
    COM_CODE      VARCHAR(4)    NOT NULL,
    BOM_DOC_TYPE  VARCHAR(4)    NOT NULL,
    BOM_DOC_NUM   VARCHAR(25)   NOT NULL,
    BOM_DOC_FROM  DATE          NOT NULL DEFAULT CURRENT_DATE,
    BOM_DOC_UNTIL DATE          NOT NULL DEFAULT CURRENT_DATE,
    MAT_DOC_TYPE  VARCHAR(4)    NOT NULL,
    MAT_DOC_NUM   VARCHAR(25)   NOT NULL,
    QUANTITY      DECIMAL(5, 2) NOT NULL,
    IS_DELETED    BOOLEAN,
    IS_PASSIVE    BOOLEAN,
    DRAW_NUM      VARCHAR(25),
    PRIMARY KEY (COM_CODE, BOM_DOC_TYPE, BOM_DOC_NUM, BOM_DOC_FROM, BOM_DOC_UNTIL, MAT_DOC_TYPE, MAT_DOC_NUM),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_bomdoctype FOREIGN KEY (BOM_DOC_TYPE) REFERENCES BSMGRIRPBOM001 (DOC_TYPE),
    CONSTRAINT fk_matdoctype FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001 (DOC_TYPE)
);

-- Urun Agacları
CREATE TABLE BSMGRIRPBOMCONTENT
(
    COM_CODE          VARCHAR(4)    NOT NULL,
    BOM_DOC_TYPE      VARCHAR(4)    NOT NULL,
    BOM_DOC_NUM       VARCHAR(25)   NOT NULL,
    BOM_DOC_FROM      DATE          NOT NULL DEFAULT CURRENT_DATE,
    BOM_DOC_UNTIL     DATE          NOT NULL DEFAULT CURRENT_DATE,
    MAT_DOC_TYPE      VARCHAR(4)    NOT NULL,
    MAT_DOC_NUM       VARCHAR(25)   NOT NULL,
    CONTENT_NUM       INTEGER       NOT NULL, --bunu kontrol et
    COMPONENT         VARCHAR(25)   NOT NULL,
    COMP_BOM_DOC_TYPE VARCHAR(4)    NOT NULL,
    COMP_BOM_DOC_NUM  VARCHAR(25)   NOT NULL,
    QUANTITY          DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (COM_CODE, BOM_DOC_TYPE, BOM_DOC_NUM, BOM_DOC_FROM, BOM_DOC_UNTIL, MAT_DOC_TYPE, MAT_DOC_NUM,
                 CONTENT_NUM),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_bomdoctype FOREIGN KEY (BOM_DOC_TYPE) REFERENCES BSMGRIRPBOM001 (DOC_TYPE),
    CONSTRAINT fk_matdoctype FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001 (DOC_TYPE)
);

-- Rotalar
CREATE TABLE BSMGRIRPROTHEAD
(
    COM_CODE      VARCHAR(4)    NOT NULL,
    ROT_DOC_TYPE  VARCHAR(4)    NOT NULL,
    ROT_DOC_NUM   VARCHAR(25)   NOT NULL,
    ROT_DOC_FROM  DATE          NOT NULL DEFAULT CURRENT_DATE,
    ROT_DOC_UNTIL DATE          NOT NULL DEFAULT CURRENT_DATE,
    MAT_DOC_TYPE  VARCHAR(4)    NOT NULL,
    MAT_DOC_NUM   VARCHAR(25)   NOT NULL,
    QUANTITY      DECIMAL(5, 2) NOT NULL,
    IS_DELETED    BOOLEAN,
    IS_PASSIVE    BOOLEAN,
    DRAW_NUM      VARCHAR(25),
    PRIMARY KEY (COM_CODE, ROT_DOC_TYPE, ROT_DOC_NUM, ROT_DOC_FROM, ROT_DOC_UNTIL, MAT_DOC_TYPE, MAT_DOC_NUM),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_rotdoctype FOREIGN KEY (ROT_DOC_TYPE) REFERENCES BSMGRIRPBOM001 (DOC_TYPE),
    CONSTRAINT fk_matdoctype FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001 (DOC_TYPE)
);

-- Rotalar
CREATE TABLE BSMGRIRPROTOPRCONTENT
(
    COM_CODE      VARCHAR(4)  NOT NULL,
    ROT_DOC_TYPE  VARCHAR(4)  NOT NULL,
    ROT_DOC_NUM   VARCHAR(25) NOT NULL,
    ROT_DOC_FROM  DATE        NOT NULL DEFAULT CURRENT_DATE,
    ROT_DOC_UNTIL DATE        NOT NULL DEFAULT CURRENT_DATE,
    MAT_DOC_TYPE  VARCHAR(4)  NOT NULL,
    MAT_DOC_NUM   VARCHAR(25) NOT NULL,
    OPR_NUM       INTEGER     NOT NULL,
    WCM_DOC_TYPE  VARCHAR(4)  NOT NULL,
    WCM_DOC_NUM   VARCHAR(25) NOT NULL,
    OPR_DOC_TYPE  VARCHAR(4)  NOT NULL,
    SETUP_TIME    DECIMAL(3, 2),
    MACHINE_TIME  DECIMAL(3, 2),
    LABOUR_TIME   DECIMAL(3, 2),
    PRIMARY KEY (COM_CODE, ROT_DOC_TYPE, ROT_DOC_NUM, ROT_DOC_FROM, ROT_DOC_UNTIL, MAT_DOC_TYPE, MAT_DOC_NUM, OPR_NUM),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_rotdoctype FOREIGN KEY (ROT_DOC_TYPE) REFERENCES BSMGRIRPBOM001 (DOC_TYPE),
    CONSTRAINT fk_matdoctype FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001 (DOC_TYPE)
    --CONSTRAINT fk_matdoctype FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPWCM001 (DOC_TYPE) -- İlişki yönünden sıkıntı var
);

-- Rotalar Agacları
CREATE TABLE BSMGRIRPROTBOMCONTENT
(
    COM_CODE      VARCHAR(4)    NOT NULL,
    ROT_DOC_TYPE  VARCHAR(4)    NOT NULL,
    ROT_DOC_NUM   VARCHAR(25)   NOT NULL,
    ROT_DOC_FROM  DATE          NOT NULL DEFAULT CURRENT_DATE,
    ROT_DOC_UNTIL DATE          NOT NULL DEFAULT CURRENT_DATE,
    MAT_DOC_TYPE  VARCHAR(4)    NOT NULL,
    MAT_DOC_NUM   VARCHAR(25)   NOT NULL,
    OPR_NUM       INTEGER       NOT NULL, --bunu kontrol et
    BOM_DOC_TYPE  VARCHAR(4)    NOT NULL,
    BOM_DOC_NUM   VARCHAR(25)   NOT NULL,
    CONTENT_NUM   VARCHAR(4)    NOT NULL,
    COMPONENT     VARCHAR(25)   NOT NULL,
    QUANTITY      DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (COM_CODE, ROT_DOC_TYPE, ROT_DOC_NUM, ROT_DOC_FROM, ROT_DOC_UNTIL, MAT_DOC_TYPE, MAT_DOC_NUM, OPR_NUM,
                 BOM_DOC_TYPE, BOM_DOC_NUM, CONTENT_NUM),
    CONSTRAINT fk_comcode FOREIGN KEY (COM_CODE) REFERENCES BSMGRIRPGEN001 (COM_CODE),
    CONSTRAINT fk_rotdoctype FOREIGN KEY (ROT_DOC_TYPE) REFERENCES BSMGRIRPBOM001 (DOC_TYPE),
    CONSTRAINT fk_matdoctype FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001 (DOC_TYPE),
    CONSTRAINT fk_bomdoctype FOREIGN KEY (BOM_DOC_TYPE) REFERENCES BSMGRIRPBOM001 (DOC_TYPE)
);