-- Material Head tablosu BSMGR0MATHEAD
CREATE TABLE BSMGRIRPMATHEAD  --> OK
(
    id              SERIAL PRIMARY KEY,
    COM_ID          INT NOT NULL ,
    DOC_TYPE        INT NOT NULL ,  --> BURASI MAT001 İLİŞKİ
    DOC_NUM         VARCHAR(25) UNIQUE NOT NULL ,
    MAT_DOC_FROM    DATE NOT NULL ,
    MAT_DOC_UNTIL   DATE NOT NULL ,
    SUPPLY_TYPE     BIT(1) NOT NULL , /* SATIN ALINAN - ÜRETİLEN */
    ST_UNIT         VARCHAR(3)  NOT NULL, /* MALZEME STOK BİRİMİ  GEN005 İLİŞKİ */
    NET_WEIGHT      DECIMAL(12) ,
    NW_UNIT         VARCHAR(3) , --> GEN005 İLE İLİŞKİ
    BRUT_WEIGHT     DECIMAL(12) ,
    BW_UNIT         VARCHAR(3) ,
    IS_BOM          BIT(1) ,
    BOM_ID     INT NOT NULL,
    ROT_ID     INT NOT NULL ,
    IS_ROUTE        BIT(1),
    IS_DELETED      BIT(1),
    IS_PASSIVE      BIT(1),
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (BOM_ID) REFERENCES BSMGRIRPBOM001(id) ON DELETE CASCADE,
    FOREIGN KEY (ROT_ID) REFERENCES BSMGRIRPROT001(id) ON DELETE CASCADE,
    FOREIGN KEY (DOC_TYPE) REFERENCES BSMGRIRPMAT001(id) ON DELETE CASCADE,

);

-- Material text tablosu BSMGR0MATTEXT
CREATE TABLE BSMGRIRPMATTEXT --> OK
(
    /* LANGUAGE ENTİTY */
    id          SERIAL PRIMARY KEY ,
    LAN_ID        INT NOT NULL ,
    MATS_TEXT   VARCHAR(50) NOT NULL ,
    MATL_TEXT   VARCHAR(250) NOT NULL,
    head_id        INT NOT NULL, /* BSMGRIRPMATHEAD ile ilişki kurulacak sütun */
    FOREIGN KEY (head_id) REFERENCES BSMGRIRPMATHEAD(id) ON DELETE CASCADE,
    FOREIGN KEY (LAN_ID) REFERENCES BSMGRIRPGEN002(id) ON DELETE CASCADE
    /* MATERIAL HEAD ENTİTY OLACAK MI? */
);

-- cost center head tablosu BSMGR0CCMHEAD
CREATE TABLE BSMGRIRPCCMHEAD( --> OK
    /* COM_CODE COMPANY ENTITY OLACAK MI? */
    id SERIAL       PRIMARY KEY ,
    COM_ID          INT NOT NULL ,
    DOC_TYPE        INT NOT NULL ,
    DOC_NUM         VARCHAR(25) UNIQUE NOT NULL ,
    CCM_DOC_FROM    DATE NOT NULL ,
    CCM_DOC_UNTIL   DATE NOT NULL ,
    /* COSTCENTER ENTITY ?? */
    IS_DELETED      BIT(1),
    IS_PASSIVE      BIT(1),
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (DOC_TYPE) REFERENCES BSMGRIRPCCM001(id) ON DELETE CASCADE

);

-- cost center text tablosu BSMGR0CCMTEXT
CREATE TABLE BSMGRIRPCCMTEXT( -- > OK
    /* LANGUAGE ENTITY ?? GEN002 */
    id SERIAL       PRIMARY KEY ,
    COM_ID          INT NOT NULL ,
    LAN_ID          INT NOT NULL ,
    CCMS_TEXT       VARCHAR(50) NOT NULL ,
    CCML_TEXT       VARCHAR(250) NOT NULL ,
    CCM_ID     INT NOT NULL ,
    FOREIGN KEY (LAN_ID) REFERENCES BSMGRIRPGEN002(id) ON DELETE CASCADE,
    FOREIGN KEY (CCM_ID) REFERENCES BSMGRIRPCCM001(id) ON DELETE CASCADE,
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE

);

-- BOM Head tablosu BSMGR0BOMHEAD
CREATE TABLE BSMGRIRPBOMHEAD( --> DOC_TYPE NASIL BAĞLANACAK
    /* 1- GEN001 */
    id              SERIAL PRIMARY KEY,
    COM_ID          INT NOT NULL ,
    MAT_DOC_TYPE    INT NOT NULL ,
    BOM_DOC_TYPE    INT NOT NULL ,
    DOC_NUM         VARCHAR(25) UNIQUE NOT NULL ,
    BOM_DOC_FROM    DATE NOT NULL ,
    BOM_DOC_UNTIL   DATE NOT NULL ,
    /* MATERIAL ENTİTY  */
    QUANTITY        DECIMAL(5) NOT NULL ,
    IS_DELETED      BIT(1) ,
    IS_PASSIVE      BIT(1) ,
    DRAW_NUM        VARCHAR(25) , /* çizim numarası (büyük ihtimal seviyeleri belirlemek için) */
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001(id) ON DELETE CASCADE,
    FOREIGN KEY (BOM_DOC_TYPE) REFERENCES BSMGRIRPBOM001(id) ON DELETE CASCADE

);

-- BOM CONTENT tablosu BSMGR0BOMCONTENT
CREATE TABLE BSMGRIRPBOMCONTENT( --> COMP_BOM_DOC_TYPE BAĞLANACAK
    /* gen001 */
    /* bom001 */
    /* material entity */
    id                  SERIAL PRIMARY KEY ,
    BOM_DOC_TYPE        INT NOT NULL ,
    MAT_DOC_TYPE        INT NOT NULL ,
    COM_ID              INT NOT NULL ,
    CONTENT_NUM         INT  UNIQUE NOT NULL ,
    COMPONENT           VARCHAR(25) NOT NULL ,
    COMP_BOM_DOC_TYPE   VARCHAR(4) NOT NULL , --> BOM001
    COMP_BOM_DOC_NUM    VARCHAR(25) NOT NULL ,
    QUANTITY            DECIMAL(5) NOT NULL ,
    CCM_ID              INT NOT NULL ,
    FOREIGN KEY (BOM_DOC_TYPE) REFERENCES BSMGRIRPBOM001(id) ON DELETE CASCADE,
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (CCM_ID) REFERENCES BSMGRIRPCCM001(id) ON DELETE CASCADE,
    FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001(id) ON DELETE CASCADE

);

-- work center Head tablosu BSMGR0WCMHEAD
CREATE TABLE BSMGRIRPWCMHEAD( --> DOC_TYPE BAĞLANACAK
    --> COM_CODE
    id                  SERIAL PRIMARY KEY ,
    COM_ID              INT NOT NULL ,
    WCM_DOC_TYPE        INT  NOT NULL ,
    DOC_NUM             VARCHAR(25) UNIQUE NOT NULL ,
    WCM_DOC_FROM        DATE NOT NULL ,
    WCM_DOC_UNTIL       DATE NOT NULL ,
    CCM_DOC_TYPE        INT NOT NULL ,
    WORK_TIME           DECIMAL(3),
    IS_DELETED          BIT(1) ,
    IS_PASSIVE          BIT(1),
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (WCMDOCTYPE) REFERENCES BSMGRIRPCCM001(id) ON DELETE CASCADE,
    FOREIGN KEY (CCM_DOC_TYPE) REFERENCES BSMGRIRPWCM001(id) ON DELETE CASCADE

);

-- work center text tablosu BSMGR0WCMTEXT
CREATE TABLE BSMGRIRPWCMTEXT(
    --> WORK CENTER ENTITY
    id              SERIAL PRIMARY KEY ,
    COM_ID          INT NOT NULL ,
    LAN_CODE          INT NOT NULL , --> GEN002
    WCM_DOC_TYPE    INT NOT NULL ,
    WCMS_TEXT       VARCHAR(50) NOT NULL ,
    WCML_TEXT       VARCHAR(250) NOT NULL ,
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (LAN_CODE) REFERENCES BSMGRIRPGEN002(id) ON DELETE CASCADE,
    FOREIGN KEY (WCM_DOC_TYPE) REFERENCES BSMGRIRPWCM001(id) ON DELETE CASCADE

);

-- work center operasyonları tablosu BSMGRIRPWCMOPR
CREATE TABLE BSMGRIRPWCMOPR(
    --> WORK CENTER ENTITY GEN001
    id SERIAL       PRIMARY KEY ,
    COM_ID          INT NOT NULL ,
    WCM_DOC_TYPE    INT NOT NULL ,
    DOC_TYPE        VARCHAR(4) UNIQUE NOT NULL ,
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (WCM_DOC_TYPE) REFERENCES BSMGRIRPWCM001(id) ON DELETE CASCADE

);

-- route Head tablosu BSMGRIRPROTHEAD
CREATE TABLE BSMGRIRPROTHEAD(
    /* GEN001 */
    /* BOMENTITY */
    id SERIAL       PRIMARY KEY ,
    COM_ID          INT NOT NULL ,
    BOM_DOC_TYPE    INT NOT NULL ,
    MAT_DOC_TYPE    INT NOT NULL ,
    ROT_DOC_FROM    DATE NOT NULL ,
    ROT_DOC_UNTIL   DATE NOT NULL ,
    /* MATERIAL ENTITY */
    QUANTITY        DECIMAL(5) NOT NULL ,
    IS_DELETED      BIT(1) ,
    IS_PASSIVE      BIT(1),
    DRAW_NUM        VARCHAR(25) ,
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (BOM_DOC_TYPE) REFERENCES BSMGRIRPBOM001(id) ON DELETE CASCADE,
    FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001(id) ON DELETE CASCADE
);

CREATE TABLE BSMGRIRPROTOPRCONTENT(
    id SERIAL       PRIMARY KEY ,
    COM_ID          INT NOT NULL ,
    ROT_DOC_TYPE    INT NOT NULL ,
    WCM_DOC_TYPE    INT NOT NULL ,
    MAT_DOC_TYPE    INT NOT NULL ,
    OPR_NUM         INT UNIQUE NOT NULL ,
    OPR_DOC_TYPE    VARCHAR(4) NOT NULL ,
    SETUP_TIME      DECIMAL(3) NOT NULL ,
    MACHINE_TIME    DECIMAL(3),
    LABOUR_TIME     DECIMAL(3),
    FOREIGN KEY (ROT_DOC_TYPE) REFERENCES BSMGRIRPROT001(id) ON DELETE CASCADE,
    FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (WCM_ID) REFERENCES BSMGRIRPWCM001(id) ON DELETE CASCADE,
    FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001(id) ON DELETE CASCADE

                                  );

CREATE TABLE BSMGRIRPROTBOMCONTENT(
    /* ROTOPRCONTENT ENTITY */
    /* COST CENTER ENTİTY */
    id SERIAL       PRIMARY KEY ,
    ROT_DOC_TYPE    INT NOT NULL ,
    COM_DOC_TYPE    INT NOT NULL ,
    BOM_DOC_TYPE    INT NOT NULL ,
    MAT_DOC_TYPE    INT NOT NULL ,
    OPR_NUM         INT UNIQUE NOT NULL ,
    /* BOM ENTITY */
    CONTENT_NUM     INT UNIQUE NOT NULL ,
    COMPONENT       VARCHAR(25) NOT NULL ,
    QUANTITY        DECIMAL(5) NOT NULL,
    FOREIGN KEY (ROT_DOC_TYPE) REFERENCES BSMGRIRPROT001(id) ON DELETE CASCADE,
    FOREIGN KEY (COM_DOC_TYPE) REFERENCES BSMGRIRPGEN001(id) ON DELETE CASCADE,
    FOREIGN KEY (BOM_DOC_TYPE) REFERENCES BSMGRIRPBOM001(id) ON DELETE CASCADE,
    FOREIGN KEY (MAT_DOC_TYPE) REFERENCES BSMGRIRPMAT001(id) ON DELETE CASCADE


);