-- Country Table
CREATE TABLE BSMGRIRPGEN003
(
    id           SERIAL PRIMARY KEY,
    COUNTRY_CODE VARCHAR(4)  NOT NULL UNIQUE,
    COUNTRY_TEXT VARCHAR(80) NOT NULL
);

-- City Table
CREATE TABLE BSMGRIRPGEN004
(
    id         SERIAL PRIMARY KEY,          -- Otomatik artan id
    CITY_CODE  VARCHAR(4)  NOT NULL UNIQUE, -- CityCode benzersiz
    CITY_TEXT  VARCHAR(80) NOT NULL,        -- Şehir metni
    COUNTRY_ID INT,
    CONSTRAINT fk_city_country FOREIGN KEY (COUNTRY_ID) REFERENCES BSMGRIRPGEN003 (id) ON DELETE SET NULL
);

-- Language Table
CREATE TABLE BSMGRIRPGEN002
(
    id       SERIAL PRIMARY KEY,          -- Otomatik artan id
    LAN_CODE VARCHAR(4)  NOT NULL UNIQUE, -- Dil kodu benzersiz
    LAN_TEXT VARCHAR(80) NOT NULL         -- Dil metni
);

-- Company Table
CREATE TABLE BSMGRIRPGEN001
(
    id       SERIAL PRIMARY KEY,          -- Otomatik artan id
    COM_CODE VARCHAR(4)  NOT NULL UNIQUE, -- Şirket kodu benzersiz
    COM_TEXT VARCHAR(80) NOT NULL         -- Şirket metni
);

-- Address Table
CREATE TABLE BSMGRIRPGEN0011
(
    id              SERIAL PRIMARY KEY, -- Otomatik artan id
    COM_CODE_ID     INT NOT NULL,       -- Şirket kodu foreign key
    COUNTRY_CODE_ID INT NOT NULL,       -- Ülke foreign key
    CITY_CODE_ID    INT NOT NULL,       -- Şehir foreign key
    ADDRESS1        TEXT,               -- Adres satırı 1
    ADDRESS2        TEXT,               -- Adres satırı 2
    CONSTRAINT fk_address_company FOREIGN KEY (COM_CODE_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_address_country FOREIGN KEY (COUNTRY_CODE_ID) REFERENCES BSMGRIRPGEN003 (id) ON DELETE CASCADE,
    CONSTRAINT fk_address_city FOREIGN KEY (CITY_CODE_ID) REFERENCES BSMGRIRPGEN004 (id) ON DELETE CASCADE
);

-- Unit Table
CREATE TABLE BSMGRIRPGEN005
(
    id             SERIAL PRIMARY KEY,
    UNIT_CODE      VARCHAR(3)  NOT NULL,
    UNIT_TEXT      VARCHAR(80) NOT NULL,
    IS_MAIN_UNIT   BOOLEAN,
    MAIN_UNIT_CODE VARCHAR(3)
);

-- Material Table
CREATE TABLE BSMGRIRPMAT001
(
    id            SERIAL PRIMARY KEY,
    DOC_TYPE      VARCHAR(4)  NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80) NOT NULL,
    IS_PASSIVE    BOOLEAN,
    COM_CODE_ID     INT NOT NULL,
    CONSTRAINT fk_address_company FOREIGN KEY (COM_CODE_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE
);

-- CostCenter Table
CREATE TABLE BSMGRIRPCCM001
(
    id            SERIAL PRIMARY KEY,
    DOC_TYPE      VARCHAR(4)  NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80) NOT NULL,
    IS_PASSIVE    BOOLEAN,
    COM_CODE_ID     INT NOT NULL,
    CONSTRAINT fk_address_company FOREIGN KEY (COM_CODE_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE
);

-- BOM Table
CREATE TABLE BSMGRIRPBOM001
(
    id            SERIAL PRIMARY KEY,
    DOC_TYPE      VARCHAR(4)  NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80) NOT NULL,
    IS_PASSIVE    BOOLEAN,
    COM_CODE_ID     INT NOT NULL,
    CONSTRAINT fk_address_company FOREIGN KEY (COM_CODE_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE
);

-- Route Table
CREATE TABLE BSMGRIRPROT001
(
    id            SERIAL PRIMARY KEY,
    DOC_TYPE      VARCHAR(4)  NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80) NOT NULL,
    IS_PASSIVE    BOOLEAN,
    COM_CODE_ID     INT NOT NULL,
    CONSTRAINT fk_address_company FOREIGN KEY (COM_CODE_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE
);

-- Work-Center Table
CREATE TABLE BSMGRIRPWCM001
(
    id            SERIAL PRIMARY KEY,
    DOC_TYPE      VARCHAR(4)  NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80) NOT NULL,
    IS_PASSIVE    BOOLEAN,
    COM_CODE_ID     INT NOT NULL,
    CONSTRAINT fk_address_company FOREIGN KEY (COM_CODE_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE
);

-- Operation Table
CREATE TABLE BSMGRIRPROT003
(
    id            SERIAL PRIMARY KEY,
    DOC_TYPE      VARCHAR(4)  NOT NULL,
    DOC_TYPE_TEXT VARCHAR(80) NOT NULL,
    IS_PASSIVE    BOOLEAN,
    COM_CODE_ID     INT NOT NULL,
    CONSTRAINT fk_address_company FOREIGN KEY (COM_CODE_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE
);

-- MaterialHeadEntity
CREATE TABLE BSMGRIRPMATHEAD --> OK
(
    id              SERIAL PRIMARY KEY,
    COM_ID          INT                                NOT NULL,
    MAT_DOC_TYPE_ID INT                                NOT NULL, --> BURASI MAT001 İLİŞKİ
    MAT_DOC_NUM     VARCHAR(25) UNIQUE                 NOT NULL,
    MAT_DOC_FROM    DATE                               NOT NULL DEFAULT CURRENT_DATE,
    MAT_DOC_UNTIL   DATE                               NOT NULL DEFAULT CURRENT_DATE,
    SUPPLY_TYPE     INT CHECK ( SUPPLY_TYPE IN (0, 1)) NOT NULL, /* SATIN ALINAN - ÜRETİLEN */
    ST_UNIT_ID      INT                                NOT NULL, /* MALZEME STOK BİRİMİ  GEN005 İLİŞKİ */
    NET_WEIGHT      DECIMAL(12, 3),
    NW_UNIT_ID      INT,                                         --> GEN005 İLE İLİŞKİ
    BRUT_WEIGHT     DECIMAL(12, 3),
    BW_UNIT_ID      INT,
    IS_BOM          INT CHECK ( SUPPLY_TYPE IN (0, 1, 2)),
    IS_ROUTE        INT CHECK ( SUPPLY_TYPE IN (0, 1, 2)),
    IS_DELETED      BOOLEAN,
    IS_PASSIVE      BOOLEAN,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_type_id FOREIGN KEY (MAT_DOC_TYPE_ID) REFERENCES BSMGRIRPMAT001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_st_unit_id FOREIGN KEY (ST_UNIT_ID) REFERENCES BSMGRIRPGEN005 (id) ON DELETE CASCADE,
    CONSTRAINT fk_nw_unit_id FOREIGN KEY (NW_UNIT_ID) REFERENCES BSMGRIRPGEN005 (id) ON DELETE CASCADE,
    CONSTRAINT fk_bw_unit_id FOREIGN KEY (BW_UNIT_ID) REFERENCES BSMGRIRPGEN005 (id) ON DELETE CASCADE
);

-- MaterialTextEntity
CREATE TABLE BSMGRIRPMATTEXT --> OK
(
    /* LANGUAGE ENTİTY */
    id               SERIAL PRIMARY KEY,
    COM_ID           INT          NOT NULL,
    LAN_ID           INT          NOT NULL,
    MATERIAL_HEAD_ID INT          NOT NULL,
    MATS_TEXT        VARCHAR(50)  NOT NULL,
    MATL_TEXT        VARCHAR(250) NOT NULL,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_lan_id FOREIGN KEY (LAN_ID) REFERENCES BSMGRIRPGEN002 (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_head_id FOREIGN KEY (MATERIAL_HEAD_ID) REFERENCES BSMGRIRPMATHEAD (id) ON DELETE CASCADE
);

--CostCenterHeadEntity
CREATE TABLE BSMGRIRPCCMHEAD
( --> OK
    /* COM_CODE COMPANY ENTITY OLACAK MI? */
    id              SERIAL PRIMARY KEY,
    COM_ID          INT                NOT NULL,
    CCM_DOC_TYPE_ID INT                NOT NULL,
    CCM_DOC_NUM     VARCHAR(25) UNIQUE NOT NULL,
    CCM_DOC_FROM    DATE               NOT NULL DEFAULT CURRENT_DATE,
    CCM_DOC_UNTIL   DATE               NOT NULL DEFAULT CURRENT_DATE,
    BASE_CCM_ID     INT,
    IS_DELETED      BOOLEAN,
    IS_PASSIVE      BOOLEAN,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_type_id FOREIGN KEY (CCM_DOC_TYPE_ID) REFERENCES BSMGRIRPCCM001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_base_ccm_id FOREIGN KEY (BASE_CCM_ID) REFERENCES BSMGRIRPCCMHEAD (id) ON DELETE CASCADE
);

--CostCenterTextEntity
CREATE TABLE BSMGRIRPCCMTEXT
( -- > OK
    /* LANGUAGE ENTITY ?? GEN002 */
    id          SERIAL PRIMARY KEY,
    COM_ID      INT          NOT NULL,
    LAN_ID      INT          NOT NULL,
    CCMS_TEXT   VARCHAR(50)  NOT NULL,
    CCML_TEXT   VARCHAR(250) NOT NULL,
    CCM_HEAD_ID INT          NOT NULL,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_lan_id FOREIGN KEY (LAN_ID) REFERENCES BSMGRIRPGEN002 (id) ON DELETE CASCADE,
    CONSTRAINT fk_ccm_head_id FOREIGN KEY (CCM_HEAD_ID) REFERENCES BSMGRIRPCCMHEAD (id) ON DELETE CASCADE
);

-- BomEntity
CREATE TABLE BSMGRIRPBOMHEAD
(
    /* 1- GEN001 */
    id              SERIAL PRIMARY KEY,
    COM_ID          INT                NOT NULL,
    MAT_HEAD_ID     INT                NOT NULL,
    BOM_DOC_TYPE_ID INT                NOT NULL,
    BOM_DOC_NUM     VARCHAR(25) UNIQUE NOT NULL,
    BOM_DOC_FROM    DATE               NOT NULL DEFAULT CURRENT_DATE,
    BOM_DOC_UNTIL   DATE               NOT NULL DEFAULT CURRENT_DATE,
    QUANTITY        DECIMAL(5, 2)      NOT NULL,
    IS_DELETED      BOOLEAN,
    IS_PASSIVE      BOOLEAN,
    DRAW_NUM        VARCHAR(25), /* çizim numarası (büyük ihtimal seviyeleri belirlemek için) */
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_mat_head_id FOREIGN KEY (MAT_HEAD_ID) REFERENCES BSMGRIRPMATHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_bom_doc_type_id FOREIGN KEY (BOM_DOC_TYPE_ID) REFERENCES BSMGRIRPBOM001 (id) ON DELETE CASCADE
);

-- BomContentEntity
CREATE TABLE BSMGRIRPBOMCONTENT
(
    id                   SERIAL PRIMARY KEY,
    COM_ID               INT         NOT NULL,
    COST_CENTER_ID       INT         NOT NULL,
    MAT_HEAD_ID          INT         NOT NULL,
    BOM_HEAD_ID          INT         NOT NULL,
    CONTENT_NUM          INT         NOT NULL, -- İLİŞKİ DEĞİL
    COMPONENT            VARCHAR(25) NOT NULL,
    COMP_BOM_DOC_TYPE_ID INT         NOT NULL, --> BOM001
    COMP_BOM_DOC_NUM     VARCHAR(25) NOT NULL,
    QUANTITY             DECIMAL(5)  NOT NULL,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_cost_center_id FOREIGN KEY (COST_CENTER_ID) REFERENCES BSMGRIRPCCMHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_mat_head_id FOREIGN KEY (MAT_HEAD_ID) REFERENCES BSMGRIRPMATHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_comp_bom_doc_type_id FOREIGN KEY (COMP_BOM_DOC_TYPE_ID) REFERENCES BSMGRIRPBOM001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_bom_head_id FOREIGN KEY (BOM_HEAD_ID) REFERENCES BSMGRIRPBOMHEAD (id) ON DELETE CASCADE

);

-- WorkCenterHeadEntity
CREATE TABLE BSMGRIRPWCMHEAD
(
    id               SERIAL PRIMARY KEY,
    COM_ID           INT                NOT NULL,
    BASE_WCM_HEAD_ID INT,
    CCM_HEAD_ID      INT,
    WCM_DOC_TYPE_ID  INT                NOT NULL,
    WCM_DOC_NUM      VARCHAR(25) UNIQUE NOT NULL,
    WCM_DOC_FROM     DATE               NOT NULL DEFAULT CURRENT_DATE,
    WCM_DOC_UNTIL    DATE               NOT NULL DEFAULT CURRENT_DATE,
    WORK_TIME        DECIMAL(3, 2),
    IS_DELETED       BOOLEAN,
    IS_PASSIVE       BOOLEAN,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_wcm_doc_type_id FOREIGN KEY (WCM_DOC_TYPE_ID) REFERENCES BSMGRIRPWCM001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_base_wcm_head_id FOREIGN KEY (BASE_WCM_HEAD_ID) REFERENCES BSMGRIRPWCMHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_ccm_head_id FOREIGN KEY (CCM_HEAD_ID) REFERENCES BSMGRIRPCCMHEAD (id) ON DELETE CASCADE

);

-- WorkCenterOprText
CREATE TABLE BSMGRIRPWCMTEXT
(
    id          SERIAL PRIMARY KEY,
    COM_ID      INT          NOT NULL,
    LAN_ID      INT          NOT NULL,
    WCMS_TEXT   VARCHAR(50)  NOT NULL,
    WCML_TEXT   VARCHAR(250) NOT NULL,
    WCM_HEAD_ID INT          NOT NULL,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_lan_id FOREIGN KEY (LAN_ID) REFERENCES BSMGRIRPGEN002 (id) ON DELETE CASCADE,
    CONSTRAINT fk_wcm_head_id FOREIGN KEY (WCM_HEAD_ID) REFERENCES BSMGRIRPWCMHEAD (id) ON DELETE CASCADE

);

-- WorkCenterOperationEntity
CREATE TABLE BSMGRIRPWCMOPR
(
    --> WORK CENTER ENTITY GEN001
    id          SERIAL PRIMARY KEY,
    COM_ID      INT        NOT NULL,
    WCM_HEAD_ID INT        NOT NULL,
    OPR_CODE    VARCHAR(4) NOT NULL,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_wcm_head_id FOREIGN KEY (WCM_HEAD_ID) REFERENCES BSMGRIRPWCMHEAD (id) ON DELETE CASCADE

);

--RotHeadEntity
CREATE TABLE BSMGRIRPROTHEAD
(
    id            SERIAL PRIMARY KEY,
    COM_ID        INT        NOT NULL,
    BOM_HEAD_ID   INT        NOT NULL,
    MAT_HEAD_ID   INT        NOT NULL,
    ROT_DOC_FROM  DATE       NOT NULL DEFAULT CURRENT_DATE,
    ROT_DOC_UNTIL DATE       NOT NULL DEFAULT CURRENT_DATE,
    QUANTITY      DECIMAL(5,2) NOT NULL,
    IS_DELETED    BOOLEAN,
    IS_PASSIVE    BOOLEAN,
    DRAW_NUM      VARCHAR(25),
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_bom_head_id FOREIGN KEY (BOM_HEAD_ID) REFERENCES BSMGRIRPBOMHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_mat_head_id FOREIGN KEY (MAT_HEAD_ID) REFERENCES BSMGRIRPMATHEAD (id) ON DELETE CASCADE
);

--RotOprContentEntity
CREATE TABLE BSMGRIRPROTOPRCONTENT
(
    id           SERIAL PRIMARY KEY,
    COM_ID       INT            NOT NULL,
    ROT_HEAD_ID  INT            NOT NULL,
    BOM_HEAD_ID  INT            NOT NULL,
    CCM_HEAD_ID  INT            NOT NULL,
    WCM_HEAD_ID  INT            NOT NULL,
    OPR_NUM      INTEGER UNIQUE NOT NULL, --burada sıkıntı olabilir. Burayı düsün :D
    OPR_CODE     VARCHAR(4)     NOT NULL, --burada sıkıntı olabilir. Burayı düsün :D
    SETUP_TIME   DECIMAL(3, 2)  NOT NULL,
    MACHINE_TIME DECIMAL(3, 2),
    LABOUR_TIME  DECIMAL(3, 2),
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_rot_head_id FOREIGN KEY (ROT_HEAD_ID) REFERENCES BSMGRIRPROTHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_ccm_head_id FOREIGN KEY (CCM_HEAD_ID) REFERENCES BSMGRIRPCCMHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_wcm_head_id FOREIGN KEY (WCM_HEAD_ID) REFERENCES BSMGRIRPWCMHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_bom_head_id FOREIGN KEY (BOM_HEAD_ID) REFERENCES BSMGRIRPBOMHEAD (id) ON DELETE CASCADE
);

--RotBomContentEntity
CREATE TABLE BSMGRIRPROTBOMCONTENT
(
    id                 SERIAL PRIMARY KEY,
    COM_ID             INT         NOT NULL,
    ROT_OPR_CONTENT_ID INT         NOT NULL,
    CCM_HEAD_ID        INT         NOT NULL,
    BOM_HEAD_ID        INT         NOT NULL,
    OPR_NUM            INT UNIQUE  NOT NULL,
    CONTENT_NUM        INT UNIQUE  NOT NULL,
    COMPONENT          VARCHAR(25) NOT NULL,
    QUANTITY           DECIMAL(5)  NOT NULL,
    CONSTRAINT fk_company_id FOREIGN KEY (COM_ID) REFERENCES BSMGRIRPGEN001 (id) ON DELETE CASCADE,
    CONSTRAINT fk_rot_opr_content_id FOREIGN KEY (ROT_OPR_CONTENT_ID) REFERENCES BSMGRIRPROTOPRCONTENT (id) ON DELETE CASCADE,
    CONSTRAINT fk_ccm_head_id FOREIGN KEY (CCM_HEAD_ID) REFERENCES BSMGRIRPCCMHEAD (id) ON DELETE CASCADE,
    CONSTRAINT fk_bom_head_id FOREIGN KEY (BOM_HEAD_ID) REFERENCES BSMGRIRPBOMHEAD (id) ON DELETE CASCADE
);