server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp
    username: iarpi
    password: iarpi
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: "classpath:db"
    enabled: true
