version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=iarpi
      - POSTGRES_USER=iarpi
      - POSTGRES_DB=ERP